@echo off
if not exist ngrok.exe (
    echo Downloading ngrok...
    curl.exe -L -o ngrok.zip "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip"
    echo Extracting ngrok...
    tar -xf ngrok.zip
)
echo Configuring...
ngrok.exe config add-authtoken 3Au3i7OsOxNwprCgHE5CdAMA4Xg_2btouU73MKs2gm1Mkt2QB
echo Starting ngrok...
start "" ngrok.exe http 5000
echo Waiting for tunnel...
timeout /t 5 /nobreak
curl http://127.0.0.1:4040/api/tunnels > my_url.json
echo Done.
